# festivals-fileserver configuration file v1.0
# TOML 1.0.0-rc.2+

[service]
bind-host = "localhost"
port = 1910
key = "TEST_SERVICE_KEY_001"
storage-url = "/srv/festivals-fileserver/images"
resized-storage-url = "/srv/festivals-fileserver/images/resized"

[tls]
festivaslapp-root-ca = "/usr/local/festivals-fileserver/ca.crt"
cert = "/usr/local/festivals-fileserver/server.crt"
key = "/usr/local/festivals-fileserver/server.key"

[heartbeat]
endpoint = "localhost"
interval = 6

[authentication]
endpoint = "localhost"

[log]
info = "/var/log/festivals-fileserver/info.log"
trace = "/var/log/festivals-fileserver/trace.log"